[project]
name = "parallel-video-io"
version = "0.1.5"
description = "Tools for reading and writing videos, and loading them efficiently with PyTorch."
authors = [
    {name = "Sibo Wang-Chen", email = "sibo.wang@epfl.ch"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10,<3.14"
dependencies = [
    "torch>=2.8,<3",
    "imageio>=2.37.0,<3",
    "imageio-ffmpeg==0.6.0",
    "torchcodec==0.7.0",
    "joblib>=1.5.1,<2",
    "tqdm>=4.67,<5",
    "numpy>=2.0,<3",
    "pytest>=8.4.2,<9",
]

[project.urls]
repository = "https://github.com/sibocw/parallel-video-io"

[tool.poetry]
packages = [{include = "pvio", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
